### ISSUE TITLE
PyCall not building

### ISSUE THREAD

**Issue by kafisatz** [JuliaPy/PyCall.jl#797]
I have set

`ENV["PYTHON"]=raw"c:\Python\Python38-32\PYTHON.EXE"`

and now `]build PyCall` is stuck in an infinite loop

How can I 'clean up' the PyCall installation ?
I tried rm and then add. But that was not sufficient. 

BTW: dose PyCall work with Python 3.8? 

I found some results on the issue below on google. It seems to be a python issue, but its not clear to me, how to fix it
Python itself seems to run just fine. 
The log is shown below.

```
To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.



  0%|          | 0/33 [00:00<?, ?it/s]
                                      
concurrent.futures.process._RemoteTraceback: 
'''
Traceback (most recent call last):
  File "concurrent\futures\process.py", line 368, in _queue_management_worker
  File "multiprocessing\connection.py", line 251, in recv
TypeError: __init__() missing 1 required positional argument: 'msg'
'''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "entry_point.py", line 69, in <module>
  File "concurrent\futures\process.py", line 484, in _chain_from_iterable_of_lists
  File "concurrent\futures\_base.py", line 611, in result_iterator
  File "concurrent\futures\_base.py", line 439, in result
  File "concurrent\futures\_base.py", line 388, in __get_result
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
[10124] Failed to execute script entry_point
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - cryptography==2.9.2=py37h7a1dbc1_0
  - win_inet_pton==1.1.0=py37_0
  - wheel==0.34.2=py37_0
  - conda-package-handling==1.6.1=py37h62dcd97_0
  - wincertstore==0.2=py37_0
  - ca-certificates==2020.1.1=0
  - ruamel_yaml==0.15.87=py37he774522_0
  - yaml==0.1.7=hc54c509_2
  - conda==4.8.3=py37_0
  - zlib==1.2.11=h62dcd97_4
  - idna==2.9=py_1
  - pip==20.0.2=py37_3
  - cffi==1.14.0=py37h7a1dbc1_0
  - pywin32==227=py37he774522_1
  - certifi==2020.4.5.1=py37_0
  - sqlite==3.31.1=h2a8f88b_1
  - chardet==3.0.4=py37_1003
  - python==3.7.7=h81c818b_4
  - requests==2.23.0=py37_0
  - console_shortcut==0.1.1=4
  - pyopenssl==19.1.0=py37_0
  - six==1.14.0=py37_0
  - menuinst==1.4.16=py37he774522_0
  - vc==14.1=h0510ff6_4
  - urllib3==1.25.8=py37_0
  - openssl==1.1.1g=he774522_0
  - powershell_shortcut==0.0.1=3
  - pycparser==2.20=py_0
  - tqdm==4.46.0=py_0
  - vs2015_runtime==14.16.27012=hf0eaf9b_1
  - pysocks==1.7.1=py37_0
  - setuptools==46.4.0=py37_0
  - pycosat==0.6.3=py37he774522_0

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch
  - https://repo.anaconda.com/pkgs/pro/win-64
  - https://repo.anaconda.com/pkgs/pro/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.



  0%|          | 0/33 [00:00<?, ?it/s]
                                      
concurrent.futures.process._RemoteTraceback: 
'''
Traceback (most recent call last):
  File "concurrent\futures\process.py", line 368, in _queue_management_worker
  File "multiprocessing\connection.py", line 251, in recv
TypeError: __init__() missing 1 required positional argument: 'msg'
'''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "entry_point.py", line 69, in <module>
  File "concurrent\futures\process.py", line 484, in _chain_from_iterable_of_lists
  File "concurrent\futures\_base.py", line 611, in result_iterator
  File "concurrent\futures\_base.py", line 439, in result
  File "concurrent\futures\_base.py", line 388, in __get_result
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
[11664] Failed to execute script entry_point
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - pycparser==2.20=py_0
  - vs2015_runtime==14.16.27012=hf0eaf9b_1
  - openssl==1.1.1g=he774522_0
  - yaml==0.1.7=hc54c509_2
  - cffi==1.14.0=py37h7a1dbc1_0
  - chardet==3.0.4=py37_1003
  - pyopenssl==19.1.0=py37_0
  - requests==2.23.0=py37_0
  - cryptography==2.9.2=py37h7a1dbc1_0
  - sqlite==3.31.1=h2a8f88b_1
  - win_inet_pton==1.1.0=py37_0
  - console_shortcut==0.1.1=4
  - pywin32==227=py37he774522_1
  - vc==14.1=h0510ff6_4
  - setuptools==46.4.0=py37_0
  - six==1.14.0=py37_0
  - wincertstore==0.2=py37_0
  - ruamel_yaml==0.15.87=py37he774522_0
  - idna==2.9=py_1
  - ca-certificates==2020.1.1=0
  - certifi==2020.4.5.1=py37_0
  - urllib3==1.25.8=py37_0
  - menuinst==1.4.16=py37he774522_0
  - conda-package-handling==1.6.1=py37h62dcd97_0
  - conda==4.8.3=py37_0
  - zlib==1.2.11=h62dcd97_4
  - python==3.7.7=h81c818b_4
  - pycosat==0.6.3=py37he774522_0
  - pip==20.0.2=py37_3
  - pysocks==1.7.1=py37_0
  - wheel==0.34.2=py37_0
  - tqdm==4.46.0=py_0
  - powershell_shortcut==0.0.1=3

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch
  - https://repo.anaconda.com/pkgs/pro/win-64
  - https://repo.anaconda.com/pkgs/pro/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.



  0%|          | 0/33 [00:00<?, ?it/s]
                                      
concurrent.futures.process._RemoteTraceback: 
'''
Traceback (most recent call last):
  File "concurrent\futures\process.py", line 368, in _queue_management_worker
  File "multiprocessing\connection.py", line 251, in recv
TypeError: __init__() missing 1 required positional argument: 'msg'
'''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "entry_point.py", line 69, in <module>
  File "concurrent\futures\process.py", line 484, in _chain_from_iterable_of_lists
  File "concurrent\futures\_base.py", line 611, in result_iterator
  File "concurrent\futures\_base.py", line 439, in result
  File "concurrent\futures\_base.py", line 388, in __get_result
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
[8924] Failed to execute script entry_point
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - cffi==1.14.0=py37h7a1dbc1_0
  - yaml==0.1.7=hc54c509_2
  - zlib==1.2.11=h62dcd97_4
  - win_inet_pton==1.1.0=py37_0
  - chardet==3.0.4=py37_1003
  - cryptography==2.9.2=py37h7a1dbc1_0
  - requests==2.23.0=py37_0
  - ca-certificates==2020.1.1=0
  - powershell_shortcut==0.0.1=3
  - console_shortcut==0.1.1=4
  - pycparser==2.20=py_0
  - conda==4.8.3=py37_0
  - six==1.14.0=py37_0
  - menuinst==1.4.16=py37he774522_0
  - certifi==2020.4.5.1=py37_0
  - setuptools==46.4.0=py37_0
  - pywin32==227=py37he774522_1
  - pycosat==0.6.3=py37he774522_0
  - vc==14.1=h0510ff6_4
  - vs2015_runtime==14.16.27012=hf0eaf9b_1
  - pyopenssl==19.1.0=py37_0
  - sqlite==3.31.1=h2a8f88b_1
  - conda-package-handling==1.6.1=py37h62dcd97_0
  - tqdm==4.46.0=py_0
  - python==3.7.7=h81c818b_4
  - urllib3==1.25.8=py37_0
  - pip==20.0.2=py37_3
  - wincertstore==0.2=py37_0
  - idna==2.9=py_1
  - openssl==1.1.1g=he774522_0
  - pysocks==1.7.1=py37_0
  - wheel==0.34.2=py37_0
  - ruamel_yaml==0.15.87=py37he774522_0

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch
  - https://repo.anaconda.com/pkgs/pro/win-64
  - https://repo.anaconda.com/pkgs/pro/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.



  0%|          | 0/33 [00:00<?, ?it/s]
                                      
concurrent.futures.process._RemoteTraceback: 
'''
Traceback (most recent call last):
  File "concurrent\futures\process.py", line 368, in _queue_management_worker
  File "multiprocessing\connection.py", line 251, in recv
TypeError: __init__() missing 1 required positional argument: 'msg'
'''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "entry_point.py", line 69, in <module>
  File "concurrent\futures\process.py", line 484, in _chain_from_iterable_of_lists
  File "concurrent\futures\_base.py", line 611, in result_iterator
  File "concurrent\futures\_base.py", line 439, in result
  File "concurrent\futures\_base.py", line 388, in __get_result
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
[6004] Failed to execute script entry_point
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - vs2015_runtime==14.16.27012=hf0eaf9b_1
  - conda==4.8.3=py37_0
  - pycosat==0.6.3=py37he774522_0
  - win_inet_pton==1.1.0=py37_0
  - pyopenssl==19.1.0=py37_0
  - setuptools==46.4.0=py37_0
  - wheel==0.34.2=py37_0
  - vc==14.1=h0510ff6_4
  - urllib3==1.25.8=py37_0
  - pycparser==2.20=py_0
  - zlib==1.2.11=h62dcd97_4
  - ruamel_yaml==0.15.87=py37he774522_0
  - yaml==0.1.7=hc54c509_2
  - cffi==1.14.0=py37h7a1dbc1_0
  - conda-package-handling==1.6.1=py37h62dcd97_0
  - tqdm==4.46.0=py_0
  - certifi==2020.4.5.1=py37_0
  - sqlite==3.31.1=h2a8f88b_1
  - chardet==3.0.4=py37_1003
  - pip==20.0.2=py37_3
  - idna==2.9=py_1
  - requests==2.23.0=py37_0
  - pywin32==227=py37he774522_1
  - six==1.14.0=py37_0
  - python==3.7.7=h81c818b_4
  - cryptography==2.9.2=py37h7a1dbc1_0
  - menuinst==1.4.16=py37he774522_0
  - wincertstore==0.2=py37_0
  - pysocks==1.7.1=py37_0
  - openssl==1.1.1g=he774522_0
  - ca-certificates==2020.1.1=0
  - powershell_shortcut==0.0.1=3
  - console_shortcut==0.1.1=4

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch
  - https://repo.anaconda.com/pkgs/pro/win-64
  - https://repo.anaconda.com/pkgs/pro/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

```

**Comment by tkf** [comment]
> How can I 'clean up' the PyCall installation ?

You can try something like

```sh
rm -rf ~/.julia/prefs/PyCall \
    ~/.julia/packages/PyCall \
    ~/.julia/compiled/*/PyCall/ \
    ~/.julia/packages/Conda \
    ~/.julia/compiled/*/Conda/ \
    ~/.julia/conda
```

Then in the Julia REPL

```
]instantiate
]build PyCall
```

> dose PyCall work with Python 3.8?

Yes.

**Comment by kafisatz** [comment]
Thanks. 
I note that this was not sufficient. The error 
``` concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.```
remained.
I uninstalled Python3.8 and installed Python3.7 and now things are working just fine. (I guess I could have reinstalled Python 3.8 just as well)
